### Returns all the users.
GET http://localhost:3000/users/


### Returns a user by their _id.
GET http://localhost:3000/users/65a027228980e4b5beca12db


### Inserts a new user into our database.
POST http://localhost:3000/users/ HTTP/1.1
Content-Type: application/json

{
    "firstname": "Zazu",
    "lastname": "Kamalenga",
    "email": "kamalengaza@byui.edu",
    "favoriteColor": "Mauve",
    "birthdate": "1993 October 18"
}


### Updates a user by their _id.
PUT http://localhost:3000/users/65a9206236cb4d9dd029dd75 HTTP/1.1
Content-Type: application/json

{
    "firstname": "Danny",
    "lastname": "Venter",
    "email": "venterdan@byui.edu",
    "favoriteColor": "Violet",
    "birthdate": "1998 December 3"
}


### Deletes user by their _id.
DELETE http://localhost:3000/users/65a924e0ba532814bbc3dfa1